#!/bin/csh
cd ./
setenv RUN ./
setenv NEWIT $RUN/structures/it1/water
if ( `ls -1 $NEWIT/analysis/*fit_*.pdb | wc -l` > 1) then
  python2 ./tools/make_contacts.py $NEWIT/analysis/*fit_*pdb
  foreach i ($NEWIT/analysis/*fit_*.contacts)
    grep -v "-" $i >$i.tmp
    \mv $i.tmp $i
  end
  python2 ./tools/calc_fcc_matrix.py $NEWIT/analysis/*fit_*contacts -o $NEWIT/analysis/complex_fcc.disp -H -H >& $NEWIT/analysis/fcc.out
  gzip -f $NEWIT/analysis/fcc.out
else
  echo "Cluster 1 -> 1" >$NEWIT/analysis/cluster.out
  touch $NEWIT/analysis/CLUST_DONE
  gzip -f $NEWIT/analysis/cluster.out
  touch $NEWIT/analysis/MTX_DONE
endif
